### ISSUE TITLE
[1.9 1.1.0.255] Giving some items in jei freezes client

### ISSUE THREAD

**Issue by jawsawn** [korti11/Transmatrics#1]
like wrench and transmitter, haven't tested for other items but hammer and blocks are not causing it.

**Comment by korti11** [comment]
That should be at the moment only for the wrench and the connector, because of the colored name. I don't know how to fix that, except to use the default color. The best way to get these items at the moment is over the creative inventory.
In the next version I change the color to the default color.

**Comment by jawsawn** [comment]
Don't think that colored name is important. This mod took my attention, so you are doing it right with the wireless! I hope you patch that asap :new_moon_with_face:

**Comment by jawsawn** [comment]
or you can ask for help in the community? I'm pretty sure somebody would love to help
