### ISSUE TITLE
[Issue] Duplicate id: TileSolarPanel

### ISSUE THREAD

**Issue by accessdenied0** [korti11/Transmatrics#2]
Hey @korti11 

I'm sorry that I can't be that exact which mod duplicates it (I guess TechReborn), but I'm not able to start the game with your mod: http://pastebin.com/CcyQFbYD

access_denied

**Comment by korti11** [comment]
Yes it was TechReborn. I looked up the source code of it and it uses the same tile entity id.

**Comment by accessdenied0** [comment]
@korti11,

Thank you for this fast fix! Do you have a release schedule for you mod?

**Comment by korti11** [comment]
The new version is up on Curse.
